version: "3"
services:
  front:
    image: kentiee/cim_front:latest
    build: .
    volumes:
      - ./app:/react
      - /react/node_modules
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    command: "/usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"
